// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package TrlInterface

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Trl struct {
	_tab flatbuffers.Table
}

func GetRootAsTrl(buf []byte, offset flatbuffers.UOffsetT) *Trl {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Trl{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Trl) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Trl) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Trl) ContainerName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Trl) ContainerID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Trl) TrlDetails(obj *TrlDetails, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Trl) TrlDetailsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func TrlStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func TrlAddContainerName(builder *flatbuffers.Builder, containerName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(containerName), 0)
}
func TrlAddContainerID(builder *flatbuffers.Builder, containerID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(containerID), 0)
}
func TrlAddTrlDetails(builder *flatbuffers.Builder, trlDetails flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(trlDetails), 0)
}
func TrlStartTrlDetailsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TrlEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
