// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package TrlInterface

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TrlDetails struct {
	_tab flatbuffers.Table
}

func GetRootAsTrlDetails(buf []byte, offset flatbuffers.UOffsetT) *TrlDetails {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TrlDetails{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TrlDetails) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TrlDetails) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TrlDetails) TrlSpec(obj *TrlSpec, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *TrlDetails) TrlSpecLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TrlDetails) RecordName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func TrlDetailsStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TrlDetailsAddTrlSpec(builder *flatbuffers.Builder, trlSpec flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(trlSpec), 0)
}
func TrlDetailsStartTrlSpecVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TrlDetailsAddRecordName(builder *flatbuffers.Builder, recordName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(recordName), 0)
}
func TrlDetailsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
