// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package TrlInterface

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TrlSpec struct {
	_tab flatbuffers.Table
}

func GetRootAsTrlSpec(buf []byte, offset flatbuffers.UOffsetT) *TrlSpec {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TrlSpec{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TrlSpec) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TrlSpec) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TrlSpec) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TrlSpec) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TrlSpec) Type() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func TrlSpecStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func TrlSpecAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func TrlSpecAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(value), 0)
}
func TrlSpecAddType(builder *flatbuffers.Builder, type_ flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(type_), 0)
}
func TrlSpecEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
