// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package TrlCimInterface

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TrlData struct {
	_tab flatbuffers.Table
}

func GetRootAsTrlData(buf []byte, offset flatbuffers.UOffsetT) *TrlData {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TrlData{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TrlData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TrlData) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TrlData) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TrlData) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TrlData) Type() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func TrlDataStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func TrlDataAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func TrlDataAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(value), 0)
}
func TrlDataAddType(builder *flatbuffers.Builder, type_ flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(type_), 0)
}
func TrlDataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
